### ISSUE TITLE
Pentaho reports are not working

### ISSUE THREAD

**Issue by luisalegria** [bharathcgowda/Fineract#1]
On 19.12 MifosX version, pentaho reports show a blank page.

This happen because Fineract has removed the Support for Pentaho reports due to some licensing issues, Hence the reports don't run on the Fineract recent releases.

**Comment by francisguchie** [comment]
@bharathcgowda 's version is different from the latest build.

In 19.2, they are using the compile command
In 19.4 its implementation command

I have tried to implement pentaho in the latest build, but i am getting an asertion error duplicate classpaths found.
